on: 
  pull_request:
    paths:
      - "src/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: npm install, build, and test
        
        run: |
          yarn install
          
      - name: workaround for detached HEAD
        run: |
          git checkout ${{github.head_ref}} || git checkout -b ${{github.head_ref}} && git pull


      - name: Build storybook
        run: |
          yarn build-storybook
        
      - name: Capture with storycap
        run: |
          npx storycap --serverCmd "npx http-server storybook-static -p 9001" http://localhost:9001 -o "actualDir" --disableCssAnimation  --parallel 12
       
      # - name: Copy
      #   run: |
      #     cp -r actualDir/* .reg/expected
      - name: run reg-suit
      
      
        run: |
          npx reg-suit run
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
